use_frameworks!

platform :ios, '9.0'

target 'yyswiftmodule_Example' do
  pod 'yyswiftmodule', :path => '../'

  target 'yyswiftmodule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
